import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Head from "next/head";
import HeadQuestionWithAccount from "../../components/atoms/header/HeadQuestionWithAccount";
import Footer from "../../components/atoms/footer/FooterComponent";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

const RootLayout: React.FC<RootLayoutProps> = ({ children }) => {
  return (
    <html lang="en">
      <Head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link href="https://fonts.googleapis.com/css2?family=Fustat:wght@200..800&display=swap" rel="stylesheet" />
      </Head>
      <body className={`${inter.className} flex flex-col justify-center bg-[rgba(243,243,243)]`}>
        <HeadQuestionWithAccount />
        {children}
        <Footer />
      </body>
    </html>
  );
};

export default RootLayout;
